import {
  Controller,
  Get,
  Post,
  Patch,
  Delete,
  Param,
  Body,
  UseGuards,
  Query,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth, ApiQuery } from '@nestjs/swagger';
import { JwtAuthGuard } from '../../application/guards/jwt-auth.guard';
import { RolesGuard } from '../../application/guards/roles.guard';
import { Roles } from '../../application/decorators/roles.decorator';
import { CurrentUser } from '../../application/decorators/current-user.decorator';
import { User } from '../../domain/entities/user.entity';
import { UserRepository } from '../../infrastructure/persistence/user.repository';
import { CreateUserDto } from '../dtos/create-user.dto';
import { UpdateUserDto } from '../dtos/update-user.dto';

/**
 * T476-T480: Admin User Management API
 *
 * Phase 11: SUPER_ADMIN 전용 사용자 관리 엔드포인트
 */
@ApiTags('Admin - Users')
@Controller('admin/users')
@UseGuards(JwtAuthGuard, RolesGuard)
@Roles('SUPER_ADMIN')
@ApiBearerAuth()
export class AdminUserController {
  constructor(private readonly userRepository: UserRepository) {}

  /**
   * T476: GET /admin/users - 전체 사용자 목록
   */
  @Get()
  @ApiOperation({
    summary: '전체 사용자 목록 조회',
    description: 'SUPER_ADMIN이 모든 사용자를 조회합니다.',
  })
  @ApiQuery({ name: 'role', required: false, enum: ['SUPER_ADMIN', 'INSTITUTION_ADMIN', 'DRIVER'] })
  @ApiQuery({ name: 'institutionId', required: false, type: String })
  @ApiQuery({ name: 'isActive', required: false, type: Boolean })
  @ApiResponse({
    status: 200,
    description: '사용자 목록 조회 성공',
  })
  async getAllUsers(
    @Query('role') role?: string,
    @Query('institutionId') institutionId?: string,
    @Query('isActive') isActive?: string,
  ) {
    // TODO: Implement filtering in repository
    const users = await this.userRepository.findAll();

    // Client-side filtering (임시)
    let filtered = users;
    if (role) {
      filtered = filtered.filter((u) => u.role === role);
    }
    if (institutionId) {
      filtered = filtered.filter((u) => u.institutionId === institutionId);
    }
    if (isActive !== undefined) {
      const activeFilter = isActive === 'true';
      filtered = filtered.filter((u) => u.isActive === activeFilter);
    }

    return {
      statusCode: 200,
      message: 'Success',
      data: filtered,
    };
  }

  /**
   * T477: POST /admin/users - 사용자 생성 (SUPER_ADMIN만)
   */
  @Post()
  @ApiOperation({
    summary: '사용자 생성',
    description: 'SUPER_ADMIN이 새 사용자를 생성합니다.',
  })
  @ApiResponse({
    status: 201,
    description: '사용자 생성 성공',
  })
  @ApiResponse({
    status: 409,
    description: '이메일이 이미 존재함',
  })
  async createUser(@Body() dto: CreateUserDto) {
    try {
      // Check if email already exists
      const existing = await this.userRepository.findByEmail(dto.email);
      if (existing) {
        return {
          statusCode: 409,
          message: 'Email already exists',
        };
      }

      const user = new User(
        '', // id will be generated by Prisma
        dto.email,
        dto.password, // Should be hashed before saving
        dto.role as any,
        dto.name,
        true, // isActive
        dto.institutionId || null,
        null, // lastLoginAt
        new Date(),
        new Date(),
      );

      const created = await this.userRepository.create(user);

      return {
        statusCode: 201,
        message: 'User created successfully',
        data: created,
      };
    } catch (error: any) {
      return {
        statusCode: 400,
        message: error.message,
      };
    }
  }

  /**
   * T478: PATCH /admin/users/:id - 사용자 정보 수정
   */
  @Patch(':id')
  @ApiOperation({
    summary: '사용자 정보 수정',
    description: 'SUPER_ADMIN이 사용자 정보를 수정합니다.',
  })
  @ApiResponse({
    status: 200,
    description: '사용자 정보 수정 성공',
  })
  @ApiResponse({
    status: 404,
    description: '사용자를 찾을 수 없음',
  })
  async updateUser(@Param('id') id: string, @Body() dto: UpdateUserDto) {
    try {
      const user = await this.userRepository.findById(id);
      if (!user) {
        return {
          statusCode: 404,
          message: 'User not found',
        };
      }

      // Update fields
      if (dto.name !== undefined) {
        user.updateName(dto.name);
      }
      if (dto.isActive !== undefined) {
        if (dto.isActive) {
          user.activate();
        } else {
          user.deactivate();
        }
      }

      const updated = await this.userRepository.update(id, {
        name: user.name,
        isActive: user.isActive,
      });

      return {
        statusCode: 200,
        message: 'User updated successfully',
        data: updated,
      };
    } catch (error: any) {
      return {
        statusCode: 400,
        message: error.message,
      };
    }
  }

  /**
   * T479: DELETE /admin/users/:id - 사용자 삭제
   */
  @Delete(':id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: '사용자 삭제',
    description: 'SUPER_ADMIN이 사용자를 삭제합니다. (본인 계정은 삭제 불가)',
  })
  @ApiResponse({
    status: 200,
    description: '사용자 삭제 성공',
  })
  @ApiResponse({
    status: 400,
    description: '본인 계정은 삭제할 수 없음',
  })
  @ApiResponse({
    status: 404,
    description: '사용자를 찾을 수 없음',
  })
  async deleteUser(@Param('id') id: string, @CurrentUser() currentUser: User) {
    try {
      // 본인 계정 삭제 방지
      if (id === currentUser.id) {
        return {
          statusCode: 400,
          message: 'Cannot delete your own account',
        };
      }

      const user = await this.userRepository.findById(id);
      if (!user) {
        return {
          statusCode: 404,
          message: 'User not found',
        };
      }

      await this.userRepository.delete(id);

      return {
        statusCode: 200,
        message: 'User deleted successfully',
      };
    } catch (error: any) {
      return {
        statusCode: 400,
        message: error.message,
      };
    }
  }
}
